#!/usr/bin/env python3
"""Generate a concise repository structure document."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "STRUCTURE.md"
EXCLUDED = {".git", ".github", "node_modules", "coverage", "dist", "build"}


def visible(path: Path) -> bool:
    return not any(part in EXCLUDED for part in path.relative_to(ROOT).parts)


def main() -> None:
    files = [path for path in ROOT.rglob("*") if path.is_file() and visible(path)]
    directories = set()
    for path in files:
        parent = path.parent
        while parent != ROOT:
            directories.add(parent)
            parent = parent.parent
    directories = set(directories)
    root_files = sorted(path for path in files if path.parent == ROOT)

    lines = [
        "# Repository Structure",
        "",
        "<!-- Generated by scripts/generate-structure.py. Do not edit manually. -->",
        "",
        "```text",
        "tasting-journals-app/",
    ]

    def add_directories(parent: Path, level: int) -> None:
        children = sorted(path for path in directories if path.parent == parent)
        for directory in children:
            lines.append(f"{'  ' * level}{directory.name}/")
            add_directories(directory, level + 1)

    add_directories(ROOT, 1)

    for path in root_files:
        lines.append(f"  {path.name}")

    lines.extend(["```", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
